import http from 'node:http';
import { readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { createHash, randomUUID } from 'node:crypto';
import { dirname, join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const dataDir = join(root, 'data');
const storePath = join(dataDir, 'store.json');
const sessions = new Map();
const types = { '.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml' };
const hash = value => createHash('sha256').update(value).digest('hex');
const defaultStore = { admin:null, settings:{ email:'siikarol10@gmail.com', hours:{ 1:['09:00','18:00'],2:['09:00','18:00'],3:['09:00','18:00'],4:['09:00','18:00'],5:['09:00','18:00'],6:['10:00','14:00'],0:null }, services:[
  {id:'klasyczny',name:'Manicure klasyczny',minutes:60},{id:'hybryda',name:'Manicure hybrydowy',minutes:90},{id:'spa-mani',name:'Manicure SPA',minutes:75},{id:'french',name:'French manicure',minutes:105},{id:'babyboomer',name:'Baby Boomer',minutes:105},{id:'zel',name:'Przedłużanie paznokci żelem',minutes:180},{id:'forma',name:'Budowa paznokci na formie',minutes:180},{id:'uzupelnienie',name:'Uzupełnienie stylizacji żelowej',minutes:150},{id:'wzmocnienie',name:'Wzmocnienie naturalnej płytki żelem',minutes:105},{id:'zmiana',name:'Zmiana stylizacji żelowej',minutes:150},{id:'naprawa',name:'Naprawa jednego paznokcia',minutes:20},{id:'pedi-klasyczny',name:'Pedicure klasyczny',minutes:75},{id:'pedicure',name:'Pedicure hybrydowy',minutes:90},{id:'pedi-spa',name:'Pedicure SPA',minutes:105},{id:'kobido',name:'Masaż Kobido',minutes:75}
 ]}, bookings:[] };
async function load(){try{return JSON.parse(await readFile(storePath,'utf8'))}catch{await mkdir(dataDir,{recursive:true});await save(defaultStore);return structuredClone(defaultStore)}}
async function save(data){await mkdir(dataDir,{recursive:true});await writeFile(storePath,JSON.stringify(data,null,2),'utf8')}
function json(res,status,body){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(body))}
async function body(req){let data='';for await(const c of req)data+=c;if(data.length>1e6)throw Error('Za duże dane');return data?JSON.parse(data):{}}
function authorized(req){const token=(req.headers.cookie||'').match(/mz_session=([^;]+)/)?.[1];return token&&sessions.has(token)}
function slots(data,date,serviceId){const service=data.settings.services.find(x=>x.id===serviceId);if(!service)return[];const day=new Date(`${date}T12:00:00`).getDay(),hours=data.settings.hours[day];if(!hours)return[];const [oh,om]=hours[0].split(':').map(Number),[ch,cm]=hours[1].split(':').map(Number);const open=oh*60+om,close=ch*60+cm;const active=data.bookings.filter(b=>b.date===date&&b.status!=='cancelled');let result=[];for(let t=open;t+service.minutes<=close;t+=15){const end=t+service.minutes;const clash=active.some(b=>{const s=data.settings.services.find(x=>x.id===b.serviceId);const bs=Number(b.time.slice(0,2))*60+Number(b.time.slice(3));return s&&t<bs+s.minutes+15&&end+15>bs});if(!clash)result.push(`${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`)}return result}
async function email(data,booking){if(!process.env.SMTP_USER||!process.env.SMTP_PASS)return;try{const nodemailer=(await import('nodemailer')).default;const s=data.settings.services.find(x=>x.id===booking.serviceId);const transport=nodemailer.createTransport({host:process.env.SMTP_HOST||'smtp.gmail.com',port:Number(process.env.SMTP_PORT||465),secure:true,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await transport.sendMail({from:process.env.MAIL_FROM||process.env.SMTP_USER,to:data.settings.email,subject:`Nowa rezerwacja: ${booking.date}, ${booking.time}`,text:`Klientka: ${booking.name}\nUsługa: ${s?.name}\nTermin: ${booking.date}, ${booking.time}\nTelefon: ${booking.phone}\nE-mail: ${booking.email}`})}catch(err){console.error('E-mail notification failed:',err.message)}}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');let data=await load();if(url.pathname==='/api/public/settings'&&req.method==='GET')return json(res,200,{configured:Boolean(data.admin),services:data.settings.services});if(url.pathname==='/api/public/slots'&&req.method==='GET')return json(res,200,{slots:slots(data,url.searchParams.get('date'),url.searchParams.get('serviceId'))});if(url.pathname==='/api/setup'&&req.method==='POST'){if(data.admin)return json(res,409,{error:'Panel jest już skonfigurowany'});const x=await body(req);if(!x.password||x.password.length<10)return json(res,400,{error:'Hasło musi mieć co najmniej 10 znaków'});data.admin={password:hash(x.password)};data.settings.email=x.email||data.settings.email;await save(data);return json(res,201,{ok:true})}if(url.pathname==='/api/login'&&req.method==='POST'){const x=await body(req);if(!data.admin||data.admin.password!==hash(x.password||''))return json(res,401,{error:'Nieprawidłowe hasło'});const token=randomUUID();sessions.set(token,Date.now());res.writeHead(200,{'Set-Cookie':`mz_session=${token}; HttpOnly; SameSite=Lax; Path=/`,'Content-Type':'application/json'});return res.end('{"ok":true}')}if(url.pathname.startsWith('/api/admin/')&&!authorized(req))return json(res,401,{error:'Zaloguj się do panelu'});if(url.pathname==='/api/admin/data'&&req.method==='GET')return json(res,200,data);if(url.pathname==='/api/admin/settings'&&req.method==='PUT'){const x=await body(req);data.settings={...data.settings,...x};await save(data);return json(res,200,{ok:true})}if(url.pathname==='/api/admin/booking'&&req.method==='PUT'){const x=await body(req);const b=data.bookings.find(v=>v.id===x.id);if(!b)return json(res,404,{error:'Nie znaleziono wizyty'});b.status=x.status;await save(data);return json(res,200,{ok:true})}if(url.pathname==='/api/public/book'&&req.method==='POST'){const x=await body(req),service=data.settings.services.find(s=>s.id===x.serviceId);if(!data.admin)return json(res,503,{error:'Rezerwacje nie są jeszcze uruchomione'});if(!service||!x.name||!x.email||!x.phone||!x.date||!x.time)return json(res,400,{error:'Uzupełnij wszystkie pola'});if(!slots(data,x.date,x.serviceId).includes(x.time))return json(res,409,{error:'Ten termin nie jest już dostępny'});const booking={id:randomUUID(),...x,status:'confirmed',createdAt:new Date().toISOString()};data.bookings.push(booking);await save(data);email(data,booking);return json(res,201,{ok:true})}const path=join(root,url.pathname==='/'?'index.html':decodeURIComponent(url.pathname));if(!path.startsWith(root))return json(res,403,{error:'Brak dostępu'});const info=await stat(path);if(!info.isFile())throw Error('Nie znaleziono');res.writeHead(200,{'Content-Type':types[extname(path)]||'application/octet-stream'});res.end(await readFile(path))}catch(err){json(res,err.message==='Nie znaleziono'?404:500,{error:err.message})}});
server.listen(process.env.PORT||3000,()=>console.log('Strona: http://localhost:3000 | Panel: http://localhost:3000/admin.html'));
